#define MEME_DIR "/home/ubuntu/meme"
#define DATA_DIR "/home/ubuntu/meme/share/meme-5.0.5" 
#define BIN_DIR "/home/ubuntu/meme/bin" 
#define LIBEXEC_DIR "/home/ubuntu/meme/libexec/meme-5.0.5" 
#define TEMP_DIR "" 
